[project]
name = "pipecat-quickstart"
version = "0.1.0"
description = "Quickstart example for building voice AI bots with Pipecat"
requires-python = ">=3.11"
dependencies = [
    "pipecat-ai[cartesia,daily,deepgram,openai,silero,webrtc,websocket,runner]>=1.7.0",
    "pipecat-ai-prebuilt"
]

[tool.uv.sources]
pipecat-ai-prebuilt = { path = "../", editable = true }

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
exclude = [".git", "*_pb2.py"]
line-length = 100

[tool.ruff.lint]
select = [
    "I", # Import rules
    "UP", # Modern Python
]